/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("SpacefarersObjectPageObjectPage journey");

        opaTest("Navigate to SpacefarersObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheSpacefarersListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheSpacefarersListGenerated.onTable().iCheckRows();
            When.onTheSpacefarersListGenerated.onTable().iPressRow(0);

            Then.onTheSpacefarersObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheSpacefarersObjectPageGenerated.iCheckNumberOfSections(3);
            When.onTheSpacefarersObjectPageGenerated.iPressSectionIconTabFilterButton("GeneralInfo");
            Then.onTheSpacefarersObjectPageGenerated.iCheckSection({ section: "GeneralInfo" });
            Then.onTheSpacefarersObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "firstName" });
            Then.onTheSpacefarersObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "lastName" });
            Then.onTheSpacefarersObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "email" });
            Then.onTheSpacefarersObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "department_ID" });
            Then.onTheSpacefarersObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "position_ID" });
            Then.onTheSpacefarersObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "position/rank" });
            When.onTheSpacefarersObjectPageGenerated.iPressSectionIconTabFilterButton("CosmicDetails");
            Then.onTheSpacefarersObjectPageGenerated.iCheckSection({ section: "CosmicDetails" });
            Then.onTheSpacefarersObjectPageGenerated.onForm({ section: "CosmicDetails" }).iCheckField({ property: "originPlanet" });
            Then.onTheSpacefarersObjectPageGenerated.onForm({ section: "CosmicDetails" }).iCheckField({ property: "stardustCollection" });
            Then.onTheSpacefarersObjectPageGenerated.onForm({ section: "CosmicDetails" }).iCheckField({ property: "wormholeNavSkill" });
            Then.onTheSpacefarersObjectPageGenerated.onForm({ section: "CosmicDetails" }).iCheckField({ property: "spacesuitColor" });
            Then.onTheSpacefarersObjectPageGenerated.onForm({ section: "CosmicDetails" }).iCheckField({ property: "status" });
            Then.onTheSpacefarersObjectPageGenerated.onForm({ section: "CosmicDetails" }).iCheckField({ property: "yearsInService" });
            When.onTheSpacefarersObjectPageGenerated.iPressSectionIconTabFilterButton("WarpLicensesFacet");
            Then.onTheSpacefarersObjectPageGenerated.iCheckSection({ section: "WarpLicensesFacet" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});